// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListRecruitmentDto : global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.ListWorkInformationDto, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The languageRequested property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.LanguageDto>? LanguageRequested { get; set; }
#nullable restore
#else
        public List<global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.LanguageDto> LanguageRequested { get; set; }
#endif
        /// <summary>The requisites property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Requisites { get; set; }
#nullable restore
#else
        public string Requisites { get; set; }
#endif
        /// <summary>The steps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Steps { get; set; }
#nullable restore
#else
        public string Steps { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.ListRecruitmentDto"/> and sets the default values.
        /// </summary>
        public ListRecruitmentDto() : base()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.ListRecruitmentDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.ListRecruitmentDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.ListRecruitmentDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "languageRequested", n => { LanguageRequested = n.GetCollectionOfObjectValues<global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.LanguageDto>(global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.LanguageDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "requisites", n => { Requisites = n.GetStringValue(); } },
                { "steps", n => { Steps = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Models.LanguageDto>("languageRequested", LanguageRequested);
            writer.WriteStringValue("requisites", Requisites);
            writer.WriteStringValue("steps", Steps);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
