// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship.Item;
namespace UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship
{
    /// <summary>
    /// Builds and executes requests for operations under \calculate-scholarship
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CalculateScholarshipRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.calculateScholarship.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship.Item.WithCareerNameItemRequestBuilder"/></returns>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship.Item.WithCareerNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("careerName", position);
                return new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship.Item.WithCareerNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship.CalculateScholarshipRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalculateScholarshipRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/calculate-scholarship", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship.CalculateScholarshipRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalculateScholarshipRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/calculate-scholarship", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
