// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.AddCareer;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.AddLanguage;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Careers;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.ListCareers;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.ListLanguages;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.SearchCareerByName;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.SearchKeyword;
using UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.WorkInformation;
namespace UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The addCareer property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.AddCareer.AddCareerRequestBuilder AddCareer
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.AddCareer.AddCareerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addLanguage property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.AddLanguage.AddLanguageRequestBuilder AddLanguage
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.AddLanguage.AddLanguageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The calculateScholarship property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship.CalculateScholarshipRequestBuilder CalculateScholarship
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.CalculateScholarship.CalculateScholarshipRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The careers property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Careers.CareersRequestBuilder Careers
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.Careers.CareersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listCareers property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.ListCareers.ListCareersRequestBuilder ListCareers
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.ListCareers.ListCareersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listLanguages property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.ListLanguages.ListLanguagesRequestBuilder ListLanguages
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.ListLanguages.ListLanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchCareerByName property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.SearchCareerByName.SearchCareerByNameRequestBuilder SearchCareerByName
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.SearchCareerByName.SearchCareerByNameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchKeyword property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.SearchKeyword.SearchKeywordRequestBuilder SearchKeyword
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.SearchKeyword.SearchKeywordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workInformation property</summary>
        public global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.WorkInformation.WorkInformationRequestBuilder WorkInformation
        {
            get => new global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.WorkInformation.WorkInformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.IS.VRCampus.Frontend.Blazor.Infrastructure.Kiota.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
