namespace UCR.ECCI.IS.VRCampus.Backend.Presentation.Dtos;

/// <summary>
/// Data Transfer Object (DTO) for adding a new career. Does not include the internal ID as it is generated by the system.
/// </summary>
/// <param name="Name">The name given to the career</param>
/// <param name="Description">A general description for the career</param>
/// <param name="SemestersNumber">The minimum number of semester required to finish the career</param>
/// <param name="Modality">The modality of the career</param>
/// <param name="DegreeTitle">The degree title awarded after graduation</param>
public record class AddCareerDto(
    string Name,
    string Description,
    int SemestersNumber,
    string Modality,
    string DegreeTitle,
    bool IsSteam
);
